import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { MemberShell } from "../../components/member-shell";
import { MemberSettingsForm } from "../../components/member-settings-form";
import { chatGPTSignOutPath, requireChatGPTUser } from "../../chatgpt-auth";
import { findMemberByEmail } from "../../../db/members";
export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Settings", robots: { index: false, follow: false } };
export default async function MemberSettingsPage() {
  const user = await requireChatGPTUser("/member/settings"); const member = await findMemberByEmail(user.email); if (!member) redirect("/onboarding");
  return <MemberShell displayName={member.display_name} active="settings"><main className="member-main settings-page"><section className="member-page-hero settings-hero"><div><p className="eyebrow eyebrow-light">Settings</p><h1>Your circle. Your boundaries.</h1><p>Keep your account, privacy, and community experience comfortable for you.</p></div><div className="settings-shield" aria-hidden="true">✓</div></section><div className="settings-layout"><nav className="settings-index" aria-label="Settings sections"><a href="#account">Account</a><a href="#privacy">Privacy & discovery</a><a href="#safety">Safety</a><a href="#access">Access</a></nav><div className="settings-content"><section id="account" className="settings-card"><p className="onboarding-step">Account</p><h2>Your sign-in</h2><div className="setting-row"><div><strong>Email confirmed through sign-in</strong><p>{user.email}</p></div><span className="status-pill">Confirmed</span></div><p className="field-help">ReeferBudz does not receive or store your password. Your email and birthday are never shown on your member profile.</p></section><MemberSettingsForm settings={{ city: member.city ?? "", region: member.region ?? "", locationVisibility: member.location_visibility, discoverable: Boolean(member.discoverable) }} /><section id="safety" className="settings-card settings-safety"><p className="onboarding-step">Safety</p><h2>Safety tools and support</h2><div className="settings-link-grid"><a href="/community-guidelines"><strong>Community Guidelines</strong><span>Review our shared promise →</span></a><a href="/safety"><strong>Safety Center</strong><span>Review privacy-aware connection guidance →</span></a><div><strong>Blocking and reports</strong><span>These tools are part of the next safety implementation phase before deeper member interaction expands.</span></div></div></section><section id="access" className="settings-card"><p className="onboarding-step">Access</p><h2>Account controls</h2><div className="account-actions"><a className="button button-secondary" href={chatGPTSignOutPath("/")}>Sign out</a><div><strong>Account export or deletion</strong><p>This account-management workflow is planned before broader member launch, but it is not active in the current member preview.</p></div></div></section></div></div></main></MemberShell>;
}
