"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
const interestOptions = ["Live music", "Gaming", "Outdoors", "Food", "Art", "Sports", "Wellness", "Movies"];
export function MemberProfileEditor({ member }: { member: { displayName: string; bio: string; interests: string[]; friendshipGoals: string } }) {
  const router = useRouter(); const [status, setStatus] = useState<"idle" | "saving" | "saved" | "error">("idle"); const [message, setMessage] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setStatus("saving"); setMessage(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/member/profile", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ displayName: form.get("displayName"), bio: form.get("bio"), friendshipGoals: form.get("friendshipGoals"), interests: form.getAll("interests") }) }); const result = (await response.json()) as { message?: string }; if (!response.ok) { setStatus("error"); setMessage(result.message ?? "We couldn’t save your profile."); return; } setStatus("saved"); setMessage("Profile saved. Your member view is up to date."); router.refresh(); }
  return <form className="member-edit-card" onSubmit={submit}><div className="member-form-heading"><div><p className="onboarding-step">Edit profile</p><h2>Tell your story</h2></div><span>Private by design</span></div><label>Display name<input name="displayName" defaultValue={member.displayName} required minLength={2} maxLength={50} autoComplete="nickname" /></label><label>About you <span>20–500 characters</span><textarea name="bio" defaultValue={member.bio} required minLength={20} maxLength={500} rows={6} /></label><fieldset><legend>Interests <span>Choose at least one</span></legend><div className="interest-checks">{interestOptions.map((interest) => <label key={interest} className="check-chip"><input type="checkbox" name="interests" value={interest} defaultChecked={member.interests.includes(interest)} />{interest}</label>)}</div></fieldset><label>Friendship goals <span>What kind of circle are you hoping to find?</span><textarea name="friendshipGoals" defaultValue={member.friendshipGoals} required minLength={10} maxLength={240} rows={4} /></label>{message && <p className={status === "error" ? "form-error" : "form-success"} role="status">{message}</p>}<div className="member-form-actions"><button className="button" type="submit" disabled={status === "saving"}>{status === "saving" ? "Saving…" : "Save profile"}</button><a href="/member">Back to Member Home</a></div></form>;
}
