"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
type Settings = { city: string; region: string; locationVisibility: "city_region" | "region_only" | "hidden"; discoverable: boolean };
export function MemberSettingsForm({ settings }: { settings: Settings }) {
  const router = useRouter(); const [status, setStatus] = useState<"idle" | "saving" | "saved" | "error">("idle"); const [message, setMessage] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setStatus("saving"); setMessage(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/member/settings", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ city: form.get("city"), region: form.get("region"), locationVisibility: form.get("locationVisibility"), discoverable: form.get("discoverable") === "on" }) }); const result = (await response.json()) as { message?: string }; if (!response.ok) { setStatus("error"); setMessage(result.message ?? "We couldn’t save your settings."); return; } setStatus("saved"); setMessage("Privacy settings saved."); router.refresh(); }
  return <form id="privacy" className="settings-card settings-form" onSubmit={submit}><p className="onboarding-step">Privacy & discovery</p><h2>Choose how you show up</h2><p>Share only the location detail that feels right. Street addresses are never requested.</p><div className="field-pair"><label>City <span>Optional</span><input name="city" defaultValue={settings.city} maxLength={80} autoComplete="address-level2" /></label><label>State or region <span>Optional</span><input name="region" defaultValue={settings.region} maxLength={80} autoComplete="address-level1" /></label></div><fieldset><legend>Location shown on your profile</legend><label className="privacy-choice"><input type="radio" name="locationVisibility" value="region_only" defaultChecked={settings.locationVisibility === "region_only"} /><span><strong>Region only</strong><small>The privacy-friendly default</small></span></label><label className="privacy-choice"><input type="radio" name="locationVisibility" value="city_region" defaultChecked={settings.locationVisibility === "city_region"} /><span><strong>City and region</strong><small>Help nearby Budz understand your general area</small></span></label><label className="privacy-choice"><input type="radio" name="locationVisibility" value="hidden" defaultChecked={settings.locationVisibility === "hidden"} /><span><strong>Hidden</strong><small>Do not show a location on your profile</small></span></label></fieldset><label className="discovery-toggle"><span><strong>Appear in Discover Budz</strong><small>Turn this off to keep your profile out of discovery.</small></span><input name="discoverable" type="checkbox" defaultChecked={settings.discoverable} /></label>{message && <p className={status === "error" ? "form-error" : "form-success"} role="status">{message}</p>}<button className="button" type="submit" disabled={status === "saving"}>{status === "saving" ? "Saving…" : "Save privacy settings"}</button></form>;
}
